### ISSUE TITLE
「quel_ic_config を使ってみる」の依存パッケージのパスが見つかりません

### ISSUE THREAD

**Issue by miyo** [quel-inc/quelware#6]
https://github.com/quel-inc/quelware/blob/main/quel_ic_config/GETTING_STARTED.md のインストール手順で，
依存パッケージをインストールする箇所で，

```
pip install dependency_pkgs/*.whl simplemulti/*.whl
```

あるいは，

```
pip install dependency_pkgs/*.whl feedback/*.whl
```

とするようにという記述がありますが，`simplemulti/*.whl` あるいは， `feedback/*.whl` に該当するパスが見当たりません．

コマンドを実行すると

```
WARNING: Requirement 'simplemulti/*.whl' looks like a filename, but the file does not exist
ERROR: *.whl is not a valid wheel filename.
```

というエラーに遭遇します．

現状のディレクトリ構成であれば，

```
pip install dependency_pkgs/*.whl dependency_pkgs/simplemulti/*.whl
```

あるいは，

```
pip install dependency_pkgs/*.whl dependency_pkgs/feedback/*.whl
```

が正しいように思うのですが，いかがでしょうか．

**Comment by yuuya-sugita** [comment]
と、思ったのですが、0.7.4ブランチを作って、そこに修正を積んでいこうと思います。

**Comment by yuuya-sugita** [comment]
[afd91ee] で対応しました。
